fix: sql exception issue
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select c.*,sa.all_price_db,sum(quantity) from commodity c,sales_record sa,sales_record_detail sad where sa.sales_record_id=sad.sales_record_id and sad.commodity_id=c.commodity_id and EXTRACT(YEAR FROM timestamp) =? and EXTRACT(MONTH FROM timestamp)=?  group by c.commodity_id ORDER BY all_price_db DESC LIMIT 10]; nested exception is java.sql.SQLSyntaxErrorException: Expression #13 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'wabm.sa.all_price_db' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

and Can't find Employee issue